name: seq_tools
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - numpy
  - pandas
  - click
  - tabulate
  - pytest
  - pytest-cov
  - ruff
  - mypy
  - pip:
    - wheel>=0.22
    - editdistance
    - vienna
