[tox]
envlist = py37, py38, py39, py310, py311, style, docs
minversion = 3.0.0

[testenv]
description = Run tests with pytest
package = editable
deps =
    pytest>=6.0
    -r{toxinidir}/requirements.txt
commands =
    pytest test/ --basetemp={envtmpdir} -v

[testenv:style]
description = Run code style checks with flake8
skip_install = true
deps =
    flake8
commands =
    flake8 seq_tools test
    
[testenv:docs]
changedir=docs/
deps =
    -r{toxinidir}/requirements.txt
    sphinx
commands =
    sphinx-build -b linkcheck ./ _build/
    sphinx-build -b html ./ _build/
